CREATE DATABASE alkemy_database;

USE alkemy_database;

  CREATE TABLE OPERATIONS (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONCEPT VARCHAR (180),
     AMOUNT DOUBLE,
     TYPE_DESCRIPTION VARCHAR(15),
     OPERATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);